### ISSUE TITLE
can not add my mac...

### ISSUE THREAD

**Issue by ahu** [movsb/macos-as-homekit-accessory#1]
Sorry to bother you!

I was able to find ‘MacOS HomeKit’ the first time, but it failed to add. After that, the kit no longer appears when I try again.

I also tried adding it manually by entering the code, but it never succeeds—I still don’t see anything in my Home app.

I even tried deleting the database folder and running `./maha` again, but that didn’t work either.

Let me know if you’d like any further adjustments!

**Comment by movsb** [comment]
Are you running Apple Silicon?

**Comment by ahu** [comment]
yes it is, and:
mac:      M1 with 14.6.1
iphone: 12 pro

**Comment by movsb** [comment]
有点儿尴尬……

不管是我自己 `make` 还是 直接下载预编译的二进制文件，均没有复现问题 😳。

我是 Apple M2 15.0.

不知道你用的哪种方法？如果是预编译的二进制，我刚才更新了一下文档，要用 `xattr` 清除一些状态位以允许运行，但是看你前面的描述，是成功跑起来过的……没法复现就不好弄😂。

**Comment by ahu** [comment]
对，直接下载的你预编译好的版本。运行后能看到这样的提示：

2024/08/08 18:12:48 2024-08-08 18:12:48.543 lock[4969:93065] lock started

**Comment by movsb** [comment]
在目录里面执行一下这个：

```
xattr -d com.apple.quarantine ./maha-darwin-arm64
xattr -d com.apple.quarantine ./maha-darwin-amd64
xattr -d com.apple.quarantine ./lock
```

后重新运行一下试试呢（把 db 删了）

**Comment by movsb** [comment]
https://github.com/user-attachments/assets/be947fc7-597f-4d7d-960f-3fb26c6fa533

如果电脑/手机开了 VPN 的话，估计有影响（不确定，比较迷）。

**Comment by movsb** [comment]
还可能与一个隐私设置相关：设置→隐私与安全性→本地网络→（你的终端），应该是打开状态。

**Comment by ahu** [comment]
感谢指导！

我又按照 [1#issuecomment-2275460460](https://github.com/movsb/macos-as-homekit-accessory/issues/1#issuecomment-2275460460) 弄了一下，在手机的家庭设置里还是看不到。

我看了视频，我第一次在输入代码后，没有成功进入后续步骤，提示我添加失败。现在因为看不见设备，尝试直接按【我的设备未在此显示】-> 【输入代码】方式添加也没有任何效果。

我也看了隐私设置，没有看到“我的终端”，所有其他 App 都是打开状态。

我电脑确实开着 VPN，第一次时也开着；我尝试关掉，似乎没影响。防火墙规则也都是放行的，会跟 IPv6 有关吗？

我再试试吧。有什么办法可以调试么？

**Comment by movsb** [comment]
调试比较麻烦，需要借助外部工具（mDNS 扫描工具😭）…… 其它的办法我也没有了，Apple 的这个 HomeKit 本身比较黑盒。

**Comment by ahu** [comment]
ok，我自己再试试。谢谢！
